### ISSUE TITLE
build fails due to wrong path

### ISSUE THREAD

**Issue by hmoffatt** [bejelith/docker_entrypoint#4]
```
Step 6/7 : COPY --from=source /tmp/build/bin/docker_entrypoint /docker_entrypoint
COPY failed: stat tmp/build/bin/docker_entrypoint: file does not exist
```

The Dockerfile assumes that the built binary will be in /tmp/build/bin but it's in /tmp/build/go/cmd/bin.

**Comment by bejelith** [comment]
i guess i need to put this in a CI :/

**Comment by bejelith** [comment]
I reworked teh build.. it should be fine now

**Comment by hmoffatt** [comment]
Thanks, it works now.

If you specify the full name of the alpine and golang repositories it will build with podman (buildah) too:

ie:
FROM docker.io/library/golang:1.18.3-alpine as source
FROM docker.io/library/alpine
