### ISSUE TITLE
output filename strips more than .template

### ISSUE THREAD

**Issue by hmoffatt** [bejelith/docker_entrypoint#8]
If the input filename is `server.properties.template` like in the README, the output filename is `server`, not `server.properties`.

```
$ env SERVER_PROPERTIES_LISTEN_ADDRESS="localhost" SERVER_PROPERTIES_LISTEN_PORT=8080 SERVER_PROPERTIES_ID=1 go/cmd/bin/docker_entrypoint -template SERVER.PROPERTIES.template /bin/true 
```

results in

```
-rw-r--r-- 1 hamish hamish   47 Jul  2 15:12 SERVER
-rw-r--r-- 1 hamish hamish   81 Jul  2 11:33 SERVER.PROPERTIES.template
```

**Comment by bejelith** [comment]
did u checkout the latest master? i remember i fixed this already 🤔

**Comment by hmoffatt** [comment]
Sorry was still running the old binary left over since before the build system fix.
